services:
  producer-bad-cert:
    build:
      context: .
      dockerfile: ./event-simulator-service/Dockerfile
    container_name: producer-bad-cert
    environment:
      KAFKA_BROKERS: kafka-0:9094,kafka-1:9094,kafka-2:9094
      KAFKA_SSL_CA_LOCATION: /pem/ca-root.pem
      KAFKA_SSL_CHECK_HOSTNAME: true
      KAFKA_SASL_USERNAME: ${PRODUCER_USER}
      KAFKA_SASL_PASSWORD: ${PRODUCER_PASSWORD}
      NUMBER_SIMULATION_PROCESSES: 8
      KAFKA_EVENT_TOPIC: ${KAFKA_EVENT_TOPIC}
    volumes:
      - ./generated/pem/ca-fail.pem:/pem/ca-root.pem
    networks:
      - kafka-net

  producer-bad-credential:
    build:
      context: .
      dockerfile: ./event-simulator-service/Dockerfile
    container_name: producer-bad-credential
    environment:
      KAFKA_BROKERS: kafka-0:9094,kafka-1:9094,kafka-2:9094
      KAFKA_SSL_CA_LOCATION: /pem/ca-root.pem
      KAFKA_SSL_CHECK_HOSTNAME: true
      KAFKA_SASL_USERNAME: bad-user
      KAFKA_SASL_PASSWORD: bad-password
      NUMBER_SIMULATION_PROCESSES: 8
      KAFKA_EVENT_TOPIC: ${KAFKA_EVENT_TOPIC}
    volumes:
      - ./generated/pem/ca-root.pem:/pem/ca-root.pem
    networks:
      - kafka-net

  consumer-bad-cert:
    build:
      context: .
      dockerfile: ./analytics-service/Dockerfile
    container_name: consumer-bad-cert
    environment:
      KAFKA_BROKERS: kafka-0:9094,kafka-1:9094,kafka-2:9094
      KAFKA_SSL_CA_LOCATION: /pem/ca-root.pem
      KAFKA_SSL_CHECK_HOSTNAME: true
      KAFKA_SASL_USERNAME: ${CONSUMER_USER}
      KAFKA_SASL_PASSWORD: ${CONSUMER_PASSWORD}
      WORKER_PROCESS_NUMBER: 8
      KAFKA_EVENT_TOPIC: ${KAFKA_EVENT_TOPIC}
      KAFKA_GROUP_ID: ${KAFKA_CONSUMER_GROUP_ID}
      GOOGLE_APPLICATION_CREDENTIALS: /secret/serviceAccountKey.json
      GCLOUD_PROJECT: ${GCLOUD_PROJECT}
      FIRESTORE_EMULATOR_HOST: ${FIRESTORE_EMULATOR_HOST}
    volumes:
      - ./generated/pem/ca-fail.pem:/pem/ca-root.pem
      - ./secret/serviceAccountKey.json:/secret/serviceAccountKey.json
    networks:
      - kafka-net
      - default

  consumer-bad-credential:
    build:
      context: .
      dockerfile: ./analytics-service/Dockerfile
    container_name: consumer-bad-credential
    environment:
      KAFKA_BROKERS: kafka-0:9094,kafka-1:9094,kafka-2:9094
      KAFKA_SSL_CA_LOCATION: /pem/ca-root.pem
      KAFKA_SSL_CHECK_HOSTNAME: true
      KAFKA_SASL_USERNAME: bad-user
      KAFKA_SASL_PASSWORD: bad-password
      WORKER_PROCESS_NUMBER: 8
      KAFKA_EVENT_TOPIC: ${KAFKA_EVENT_TOPIC}
      KAFKA_GROUP_ID: ${KAFKA_CONSUMER_GROUP_ID}
      GOOGLE_APPLICATION_CREDENTIALS: /secret/serviceAccountKey.json
      GCLOUD_PROJECT: ${GCLOUD_PROJECT}
      FIRESTORE_EMULATOR_HOST: ${FIRESTORE_EMULATOR_HOST}
    volumes:
      - ./generated/pem/ca-root.pem:/pem/ca-root.pem
      - ./secret/serviceAccountKey.json:/secret/serviceAccountKey.json
    networks:
      - kafka-net
      - default
networks:
  kafka-net:
    name: kafka-network
    driver: bridge
    external: true
