services:
  producer:
    build:
      context: .
      dockerfile: ./event-simulator-service/Dockerfile
    container_name: producer
    environment:
      DATA_PATH: ./data
      KAFKA_BROKERS: kafka-0:9094
      KAFKA_EVENT_TOPIC: ${KAFKA_EVENT_TOPIC}
      KAFKA_SSL_CA_LOCATION: /pem/ca-root.pem
      KAFKA_SSL_CHECK_HOSTNAME: true
      KAFKA_SASL_USERNAME: producer-user
      KAFKA_SASL_PASSWORD: producer-secret
      NUMBER_SIMULATION_PROCESSES: 4
      MIN_SESSION_INTERVAL_SECONDS: 1
      MAX_SESSION_INTERVAL_SECONDS: 10
      MIN_EVENT_INTERVAL_SECONDS: 1
      MAX_EVENT_INTERVAL_SECONDS: 10
    volumes:
      - ./pem/ca-root.pem:/pem/ca-root.pem
    networks:
      - kafka-net

  consumer:
    build:
      context: .
      dockerfile: ./analytics-service/Dockerfile
    container_name: consumer
    environment:
      KAFKA_BROKERS: kafka-0:9094
      KAFKA_GROUP_ID: analytics-service
      KAFKA_EVENT_TOPIC: e-commerce-events
      KAFKA_SSL_CA_LOCATION: /pem/ca-root.pem
      KAFKA_SSL_CHECK_HOSTNAME: true
      KAFKA_SASL_USERNAME: consumer-user
      KAFKA_SASL_PASSWORD: consumer-secret
      WORKER_PROCESS_NUMBER: 8
      GOOGLE_APPLICATION_CREDENTIALS: /secret/serviceAccountKey.json
      GCLOUD_PROJECT: ecommerce-kafka-analytic-b9267
      FIRESTORE_EMULATOR_HOST: host.docker.internal:8080
    volumes:
      - ./pem/ca-root.pem:/pem/ca-root.pem
      - ./secret/serviceAccountKey.json:/secret/serviceAccountKey.json
    networks:
      - kafka-net
      - default

networks:
  kafka-net:
    external: true
    name: kafka-network