services:
  zookeeper:
    image: bitnami/zookeeper:3.5
    container_name: zookeeper
    ports:
      - "2181"
    environment:
      ZOO_ENABLE_AUTH: yes
      ZOO_SERVER_USERS: admin
      ZOO_SERVER_PASSWORDS: admin-secret
      ZOO_CLIENT_USER: admin
      ZOO_CLIENT_PASSWORD: admin-secret
      ZOO_LISTEN_ALL_IPS: yes
    networks:
      - kafka-net

  kafka-0:
    image: bitnami/kafka:2.8.1
    container_name: kafka-0
    ports:
      - "29093:29093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_CFG_BROKER_ID: 0
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: SSL:SSL,SASL_SSL:SASL_SSL,EXTERNAL:SASL_SSL
      KAFKA_CFG_LISTENERS: SSL://:9093,SASL_SSL://:9094,EXTERNAL://:29093
      KAFKA_CFG_ADVERTISED_LISTENERS: SSL://kafka-0:9093,SASL_SSL://kafka-0:9094,EXTERNAL://localhost:29093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: SSL

      # SSL Configuration
      KAFKA_CFG_SSL_KEYSTORE_LOCATION: /opt/bitnami/kafka/config/certs/kafka.keystore.jks
      KAFKA_CFG_SSL_TRUSTSTORE_LOCATION: /opt/bitnami/kafka/config/certs/kafka.truststore.jks
      KAFKA_CFG_SSL_KEYSTORE_PASSWORD: ${KAFKA_SSL_PASSWORD}
      KAFKA_CFG_SSL_KEY_PASSWORD: ${KAFKA_SSL_PASSWORD}
      KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD: ${KAFKA_SSL_PASSWORD}

      # SASL Configuration
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256

      # ACL Configuration
      KAFKA_CFG_SUPER_USERS: User:admin
      KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true
    volumes:
      - ./keystore/kafka-0.server.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
      - ./truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro
      - ./config/kafka_jaas.conf:/opt/bitnami/kafka/config/kafka_jaas.conf:ro
      - ./config/command.properties:/opt/bitnami/kafka/config/command.properties:ro
    networks:
      - kafka-net

  kafka-init:
    image: bitnami/kafka:2.8.1
    container_name: kafka-init
    restart: "no"
    depends_on:
      - kafka-0
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-0:9093
      COMMAND_PROPERTIES: /opt/bitnami/kafka/config/command.properties
    volumes:
      - ./truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro
      - ./config/command.properties:/opt/bitnami/kafka/config/command.properties:ro
      - ./scripts/kafka-init.sh:/kafka-init.sh:ro
    command: [ "bash", "/kafka-init.sh" ]
    networks:
      - kafka-net

networks:
  kafka-net:
    name: kafka-network
    driver: bridge